/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.simschla.rebootbot

import ch.simschla.rebootbot.domain.internetbox.InternetBoxUi
import java.net.URL

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val internetBoxUi = InternetBoxUi(URL("https://192.168.1.1"))
    internetBoxUi.rebootBox()
}
